############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Blogs"
url = "blog/"
weight = 2

[[main]]
name = "Projects"
url = "project/"
weight = 3

[[main]]
name = "Sessions"
url = "session/"
weight = 4

[[main]]
name = "Hackathons"
url = "hackathon/"
weight = 5

[[main]]
name = "Team"
url = "#team-row"
weight = 6



# [[main]]
#weight = 5
#name = "More"
#hasChildren = true

# [[main]]
# parent = "More"
# name = "Service"
#url = "service/"
#weight = 1

#[[main]]
#parent = "More"
#name = "Pricing"
#url = "pricing/"
#weight = 2

#[[main]]
#parent = "More"
#name = "FAQ"
#url = "faq/"
#weight = 3
  
#[[main]]
#name = "Contact"
#url = "contact/"
#weight = 6


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Team"
url = "#team-row"
weight = 3

[[footer]]
name = "Discord"
url = ""
weight = 4

[[footer]]
name = "Github"
url = ""
weight = 5

[[footer]]
name = "Blogs"
url = "blog/"
weight = 6
