
############################# Contact Us ########################
[[ contactus ]]
name = "Sana B"
description = "Coordinator"
phone = "+91896465465"

[[ contactus ]]
name = "Varun"
description = "Coordinator"
phone = "+91896465465"

############################# social site ########################
 # themify icon : https://themify.me/themify-icons
[[social]]
title = "facebook"
icon = "fab fa-facebook"
link = "https://www.facebook.com/elektronica.iith/"

[[social]]
title = "instagram"
icon = "fab fa-instagram"
link = "https://www.instagram.com/elektronica_iith/"

[[social]]
title = "github"
icon = "fab fa-github"
link = "https://github.com/elektronicaIITH"
